reinstate master

diff --git a/tools/enigma2.sh.in b/tools/enigma2.sh.in
--- a/tools/enigma2.sh.in
+++ b/tools/enigma2.sh.in
@@ -4,6 +4,76 @@ prefix=@prefix@
 exec_prefix=@exec_prefix@
 datarootdir=@datarootdir@
 
+# set TASKSETVALUE to start enigma2
+if [ -f /proc/stb/info/chipset ]; then
+  BOXCHIPSET=$(head /proc/stb/info/chipset)
+else
+  BOXCHIPSET='unknown'
+fi
+
+case "$BOXCHIPSET" in
+bcm7356|bcm7362|bcm73625|bcm7252s )
+  TASKSETVALUE=2;;
+* )
+  TASKSETVALUE=1;;
+esac
+
+# disable oom killer
+# echo 99 >/proc/sys/vm/overcommit_ratio
+# echo 2 >/proc/sys/vm/overcommit_memory
+
+# check for /etc/enigma2 folder
+if [ ! -d /etc/enigma2 ] ; then
+	mkdir -p /etc/enigma2
+fi
+
+# workaround for old libssl
+if [ -h @libdir@/libssl.so.0.9.8 ]; then
+	echo "Found symlink @libdir@/libssl.so.0.9.8"
+else
+	ln -s @libdir@/libssl.so.1.0.0 @libdir@/libssl.so.0.9.8
+fi
+
+# workaround for old libcrypto
+if [ -h @libdir@/libcrypto.so.0.9.8 ]; then
+	echo "Found symlink @libdir@/libcrypto.so.0.9.8"
+else
+	ln -s @libdir@/libcrypto.so.1.0.0 @libdir@/libcrypto.so.0.9.8
+fi
+
+# workaround for corrupt ssl files
+if [ ! "$(grep config.misc.firstrun /etc/enigma2/settings)" == "config.misc.firstrun=false" ]; then
+	rm -rf /etc/enigma2/cert.pem &
+	rm -rf /etc/enigma2/key.pem &
+fi
+
+## update NTP time if NTP Time Enabled
+#if [ "$(grep config.misc.SyncTimeUsing /etc/enigma2/settings)" == "config.misc.SyncTimeUsing=1" ]; then
+#	/usr/sbin/ntpdate -s -u pool.ntp.org &
+#fi
+
+# update permissions of autofs config files
+#if [ ! -f /etc/auto.network ] ; then
+# chmod 640 /etc/auto.network
+# chmod 644 /etc/auto.master
+# chmod 755 /etc/auto.net
+# /etc/init.d/autofs restart
+#fi
+
+# remove annoying WebInterface relicts
+#if [ -d @libdir@/enigma2/python/Plugins/Extensions/WebInterface/ ]; then
+#	rm -rf @libdir@/enigma2/python/Plugins/Extensions/WebInterface/
+#fi
+
+if [ -e /proc/stb/info/boxtype ]; then
+	stbcheck=`cat /proc/stb/info/boxtype`
+	if [ $stbcheck == "gbmv200" ]; then
+		count=`ps -ef |grep libreader |grep -v "grep" |wc -l`
+		if [ 0 == $count ];then
+			libreader 720P_50
+		fi
+	fi
+fi
 if [ -x @bindir@/showiframe ]; then
 	if [ -f @sysconfdir@/enigma2/backdrop.mvi ]; then
 		@bindir@/showiframe @sysconfdir@/enigma2/backdrop.mvi
@@ -24,100 +94,86 @@ if [ -d /home/root ]; then
 	cd
 fi
 
-# any debuglevel passed?
-if [ -z $ENIGMA_DEBUG_LVL ]; then
-	DEBUG_LVL=3
+# check for sundtek tuner helper lib
+if [ -e /opt/lib/libmediaclient.so ]; then
+	LIBS="/opt/lib/libmediaclient.so @libdir@/libopen.so.0.0.0"
 else
-	DEBUG_LVL=$ENIGMA_DEBUG_LVL
+	LIBS="@libdir@/libopen.so.0.0.0"
 fi
 
-LIBS=@libdir@/libopen.so.0.0.0
+sync
 
-# enigma main loop
-while : ; do
+# init script for sysctl is missing, so manually load /etc/sysctl.conf here
+sysctl -p
 
-	# start enigma
-	sync
-	if [ $ENIGMA_DEBUG_LVL -lt 4 ]; then
-		LD_PRELOAD=$LIBS ENIGMA_DEBUG_LVL=$DEBUG_LVL @bindir@/enigma2
-	else
-		LD_PRELOAD=$LIBS ENIGMA_DEBUG_LVL=$DEBUG_LVL @bindir@/enigma2 > /home/root/enigma.log 2&>1
+# adjust oom score enigma2
+#(sleep 2; echo "enigma2 is the main pvr application... adjust oom score!"; PID=$(pidof enigma2); \
+#	[ -e /proc/$PID/oom_score_adj ] && echo "-999" > /proc/$PID/oom_score_adj || echo "-17" > /proc/$PID/oom_adj;) &
+
+if [ "$(grep config.crash.enabledebug /etc/enigma2/settings)" == "config.crash.enabledebug=true" ]; then
+	RANDOMIZE1970=''
+	time=`date +%Y` ;
+	if [ "$time" = 1970 ]; then
+		RANDOMIZE1970="$(strings /dev/urandom | grep -o '[[:alnum:]]' | head -n 5 | tr -d '\n')"
 	fi
+	if [ "$(grep config.crash.debug_path= /etc/enigma2/settings | sed 's/config.crash.debug_path=//g')" != "" -a -d "$(grep config.crash.debug_path= /etc/enigma2/settings | sed 's/config.crash.debug_path=//g')" ]; then
+		LD_PRELOAD=$LIBS taskset $TASKSETVALUE @bindir@/enigma2 --debug-no-color &> $(grep config.crash.debug_path= /etc/enigma2/settings | sed 's/config.crash.debug_path=//g')Enigma2-debug-$(date +%Y%m%d_%H-%M-%S)$RANDOMIZE1970.log
+	else
+		LD_PRELOAD=$LIBS taskset $TASKSETVALUE @bindir@/enigma2 --debug-no-color &> /home/root/logs/Enigma2-debug-$(date +%Y%m%d_%H-%M-%S)$RANDOMIZE1970.log
+	fi
+else
+	# in case $TERM is "linux" the serial output is activated - discard debug output
+	if [ "$TERM" = linux ]; then
+		LD_PRELOAD=$LIBS taskset $TASKSETVALUE @bindir@/enigma2 2> /dev/null
+	else
+		LD_PRELOAD=$LIBS taskset $TASKSETVALUE @bindir@/enigma2
+	fi
+fi
 
+# enigma2 exit codes:
+#
+# 1 - halt
+# 2 - reboot
+# 3 - restart enigma
+#
+# >128 signal
 
-	# enigma2 exit codes:
-	#
-	#  1 - halt
-	#  2 - reboot
-	#  3 - restart enigma in normal mode
-	#  4 - front processor upgrade
-	#  5 - install new settings
-	#  6 - restart enigma in debug mode
-	# 42 - offline update
-	# 43 - restart for autoinstall
-	#
-	# >128 signal
-
-	ret=$?
-	case $ret in
-		1)
-			/sbin/halt
-			;;
-		2)
-			/sbin/reboot
-			;;
-		3)
-			DEBUG_LVL=3
-			;;
-		4)
-			/sbin/rmmod lcd
-			/usr/sbin/fpupgrade --upgrade 2>&1 | tee /home/root/fpupgrade.log
-			sleep 1;
-			/sbin/rmmod fp
-			/sbin/modprobe fp
-			/sbin/reboot
-			;;
-		5)
-			if ! grep -q config.misc.RestartUI /etc/enigma2/settings; then
-				echo "config.misc.RestartUI=true" >>/etc/enigma2/settings
-			fi
-			;;
-		6)
-			DEBUG_LVL=4
-			;;
-		42)
-			df -P | grep -v "tmpfs " | awk '{print $6}' | tail -n +3 > /tmp/upgrade_mountpoints.txt
-			while read line; do
-				if [  -f $line/var/lib/opkg/status ]; then
-				DESTS=$DESTS" --add-dest "$line":"$line
-			fi
-			done < /tmp/upgrade_mountpoints.txt
-			# bind the console (when available)
-			[ -f /sys/class/vtconsole/vtcon1/bind ] && echo 1 > /sys/class/vtconsole/vtcon1/bind
-			( opkg upgrade sysvinit && opkg upgrade sysvinit-pidof && opkg upgrade initscripts-functions && opkg upgrade busybox && opkg upgrade kmod && opkg list-upgradable $DESTS | cut -f 1 -d ' ' | xargs opkg upgrade $DESTS ) 2>&1 | tee /home/root/ipkgupgrade.log
-			/sbin/reboot
-			;;
-		43)
-			#auto install and autobackup
-			[ -f /sys/class/vtconsole/vtcon1/bind ] && echo 1 > /sys/class/vtconsole/vtcon1/bind
-			/etc/init.d/settings-restore.sh
-			/etc/init.d/avahi-daemon stop
-			ifdown eth1
-			ip addr flush dev eth1 scope global
-			ifdown eth0
-			ip addr flush dev eth0 scope global
-			/etc/init.d/networking stop
-			killall -9 udhcpc
-			rm /var/run/udhcpc*
-			/etc/init.d/dbus-1 reload
-			/etc/init.d/networking start
-			/etc/init.d/avahi-daemon start
-			touch /etc/.doAutoinstall
-			break
-			;;
-		*)
-			break
-			;;
-	esac
-
-done
+ret=$?
+if [ "$ret" -ne "1" ]; then
+	if [ -e /proc/stb/info/boxtype ]; then
+		stbcheck=`cat /proc/stb/info/boxtype`
+		if [ $stbcheck == "gbmv200" ] ; then
+			killall -9 libreader; sleep 5
+		fi
+	fi
+fi
+case $ret in
+	1)
+		/sbin/halt
+		;;
+	2)
+		/sbin/reboot
+		;;
+	3)
+		;;
+	4)
+		/sbin/rmmod lcd
+		/usr/sbin/fpupgrade --upgrade 2>&1 | tee /home/root/fpupgrade.log
+		sleep 1;
+		/sbin/rmmod fp
+		/sbin/modprobe fp
+		/sbin/reboot
+		;;
+	42)
+		# bind the console (when available)
+		[ -f /sys/class/vtconsole/vtcon1/bind ] && echo 1 > /sys/class/vtconsole/vtcon1/bind
+		opkg upgrade 2>&1 | tee /home/root/ipkgupgrade.log
+		/sbin/reboot
+		;;
+	43)
+		echo "    " > /dev/lcd0
+		/usr/bin/gigablue_wol
+		;;
+	*)
+		;;
+esac
